# Issue 16593: Spurious solution for trig formula in Maxima

archive/issues_016356.json:
```json
{
    "body": "Reported at [this SF bug](https://sourceforge.net/p/maxima/bugs/2773/), we have \n\n```\nsolve([sin(cos(x))/cos(x)==0],x) gives: \n[x == 1/2*pi]\n```\n\n**Upstream:** Reported upstream. No feedback yet.\n\nIssue created by migration from https://trac.sagemath.org/ticket/16593\n\n",
    "created_at": "2014-06-30T14:10:21Z",
    "labels": [
        "component: calculus",
        "bug"
    ],
    "title": "Spurious solution for trig formula in Maxima",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/16593",
    "user": "https://github.com/kcrisman"
}
```
Reported at [this SF bug](https://sourceforge.net/p/maxima/bugs/2773/), we have 

```
solve([sin(cos(x))/cos(x)==0],x) gives: 
[x == 1/2*pi]
```

**Upstream:** Reported upstream. No feedback yet.

Issue created by migration from https://trac.sagemath.org/ticket/16593





---

archive/issue_events_149658.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-08-10T16:51:03Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/16593",
    "milestone": "sage-6.3",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/16593#event-149658"
}
```



---

archive/issue_events_149659.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-08-10T16:51:03Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/16593",
    "milestone": "sage-6.4",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/16593#event-149659"
}
```



---

archive/issue_comments_218476.json:
```json
{
    "body": "<a id='comment:2'></a>\nIs this issue fixed now?",
    "created_at": "2017-03-04T00:54:49Z",
    "issue": "https://github.com/sagemath/sage/issues/16593",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/16593#issuecomment-218476",
    "user": "https://trac.sagemath.org/admin/accounts/users/jakobkroeker"
}
```

<a id='comment:2'></a>
Is this issue fixed now?



---

archive/issue_events_149660.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-12-29T01:28:25Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/16593",
    "milestone": "sage-6.4",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/16593#event-149660"
}
```
