# Issue 25212: Fix malformatted test in sage.repl.ipython_extension

archive/issues_024975.json:
```json
{
    "body": "For some reason that I don't yet understand, on the main develop branch of Sage, the doctest runner is not complaining about this test even though it's syntactically malformatted.  Whereas on my Python 3 branch it is correctly reported as a syntax error.\n\n**Branch:** [u/embray/misc/cython-cell-magic-test](https://github.com/sagemath/sagetrac-mirror/tree/u/embray/misc/cython-cell-magic-test)\n\n**Commit:** [3cd27b83ef288696c7fc70eb5419be1085a3d175](https://github.com/sagemath/sagetrac-mirror/commit/3cd27b83ef288696c7fc70eb5419be1085a3d175)\n\n**Author:** Erik Bray\n\nIssue created by migration from https://trac.sagemath.org/ticket/25212\n\n",
    "closed_at": "2018-08-10T14:43:56Z",
    "created_at": "2018-04-19T09:02:32Z",
    "labels": [
        "component: misc",
        "minor",
        "bug",
        "duplicate"
    ],
    "title": "Fix malformatted test in sage.repl.ipython_extension",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/25212",
    "user": "https://github.com/embray"
}
```
For some reason that I don't yet understand, on the main develop branch of Sage, the doctest runner is not complaining about this test even though it's syntactically malformatted.  Whereas on my Python 3 branch it is correctly reported as a syntax error.

**Branch:** [u/embray/misc/cython-cell-magic-test](https://github.com/sagemath/sagetrac-mirror/tree/u/embray/misc/cython-cell-magic-test)

**Commit:** [3cd27b83ef288696c7fc70eb5419be1085a3d175](https://github.com/sagemath/sagetrac-mirror/commit/3cd27b83ef288696c7fc70eb5419be1085a3d175)

**Author:** Erik Bray

Issue created by migration from https://trac.sagemath.org/ticket/25212





---

archive/issue_events_225923.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-04-19T09:03:04Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25212#event-225923"
}
```



---

archive/issue_comments_388087.json:
```json
{
    "body": "<a id='comment:2'></a>\nShouldn't the test be:\n\n```\nsage: shell.run_cell('f()')\n```\nAdmittedly, I don't know exactly what is going on, but it looks like a different test.",
    "created_at": "2018-04-19T21:56:57Z",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/25212#issuecomment-388087",
    "user": "https://github.com/tscrim"
}
```

<a id='comment:2'></a>
Shouldn't the test be:

```
sage: shell.run_cell('f()')
```
Admittedly, I don't know exactly what is going on, but it looks like a different test.



---

archive/issue_events_225924.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2018-04-20T10:16:51Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25212#event-225924"
}
```



---

archive/issue_events_225925.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2018-04-20T10:16:51Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "label": "needs work",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25212#event-225925"
}
```



---

archive/issue_comments_388088.json:
```json
{
    "body": "<a id='comment:4'></a>\nIn other words, the right fix might be to replace\n\n```\n            ....: shell.run_cell('f()')\n```\nby\n\n```\n            sage: shell.run_cell('f()')\n```\ninstead of replacing it by\n\n```\n            sage: f()\n```",
    "created_at": "2018-04-20T10:57:41Z",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/25212#issuecomment-388088",
    "user": "https://github.com/slel"
}
```

<a id='comment:4'></a>
In other words, the right fix might be to replace

```
            ....: shell.run_cell('f()')
```
by

```
            sage: shell.run_cell('f()')
```
instead of replacing it by

```
            sage: f()
```



---

archive/issue_events_225926.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-04-20T13:58:51Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "label": "needs work",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25212#event-225926"
}
```



---

archive/issue_events_225927.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-04-20T13:58:51Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25212#event-225927"
}
```



---

archive/issue_comments_388089.json:
```json
{
    "body": "<a id='comment:5'></a>\nIt actually isn't.  I fact the latter won't work (it produces a `NameError`).  I'm not exactly sure why that is the case--I don't know how `get_test_shell` handles namespaces.  But I had that thought at first two and it does not work.  Compare also to the `%%fortran` test in the same module.",
    "created_at": "2018-04-20T13:58:51Z",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/25212#issuecomment-388089",
    "user": "https://github.com/embray"
}
```

<a id='comment:5'></a>
It actually isn't.  I fact the latter won't work (it produces a `NameError`).  I'm not exactly sure why that is the case--I don't know how `get_test_shell` handles namespaces.  But I had that thought at first two and it does not work.  Compare also to the `%%fortran` test in the same module.



---

archive/issue_comments_388090.json:
```json
{
    "body": "<a id='comment:6'></a>\nI guess you are defeating the whole purpose of the test then....",
    "created_at": "2018-04-20T14:02:02Z",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/25212#issuecomment-388090",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:6'></a>
I guess you are defeating the whole purpose of the test then....



---

archive/issue_events_225928.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2018-04-20T14:02:02Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25212#event-225928"
}
```



---

archive/issue_events_225929.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2018-04-20T14:02:02Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "label": "needs info",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25212#event-225929"
}
```



---

archive/issue_comments_388091.json:
```json
{
    "body": "<a id='comment:7'></a>\nIt's not, nor do I think you're correctly interpreting the purpose of the test.\n\nI think the issue is this: `cython_compile` injects its result directly into the actual global namespace (`user_globals`).  `get_test_shell()` meanwhile implements a fake IPython shell for testing features thereof, ~~but takes care not to modify the actual global namespace~~ this appears to not exactly be true, but there's still something going on with how `cython_compile()` uses `user_globals`, and similarly with fortran I think.\n\nThat said, all the test is testing in this case is that `%%cython` magic works, like, syntactically.  So I think it's beside the point.",
    "created_at": "2018-04-20T14:06:41Z",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/25212#issuecomment-388091",
    "user": "https://github.com/embray"
}
```

<a id='comment:7'></a>
It's not, nor do I think you're correctly interpreting the purpose of the test.

I think the issue is this: `cython_compile` injects its result directly into the actual global namespace (`user_globals`).  `get_test_shell()` meanwhile implements a fake IPython shell for testing features thereof, ~~but takes care not to modify the actual global namespace~~ this appears to not exactly be true, but there's still something going on with how `cython_compile()` uses `user_globals`, and similarly with fortran I think.

That said, all the test is testing in this case is that `%%cython` magic works, like, syntactically.  So I think it's beside the point.



---

archive/issue_events_225930.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-04-20T14:06:52Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "label": "needs info",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25212#event-225930"
}
```



---

archive/issue_events_225931.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-04-20T14:06:52Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25212#event-225931"
}
```



---

archive/issue_comments_388092.json:
```json
{
    "body": "<a id='comment:9'></a>\nOk, I take it back.  It seems like this does work at the command-line, but it does not work correctly in the doctests themselves.  So there's a weird interaction between the doctest runner, the test shell, and user_globals. \n\nI think that problem must have existed for a while though considering that\n\na) This test was already broken for a long time but not being run.\n\nand\n\nb) The other similar test in this module seems to already be working around the same issue.",
    "created_at": "2018-04-20T14:22:03Z",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/25212#issuecomment-388092",
    "user": "https://github.com/embray"
}
```

<a id='comment:9'></a>
Ok, I take it back.  It seems like this does work at the command-line, but it does not work correctly in the doctests themselves.  So there's a weird interaction between the doctest runner, the test shell, and user_globals. 

I think that problem must have existed for a while though considering that

a) This test was already broken for a long time but not being run.

and

b) The other similar test in this module seems to already be working around the same issue.



---

archive/issue_events_225932.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-04-20T14:22:03Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25212#event-225932"
}
```



---

archive/issue_events_225933.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-04-20T14:22:03Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "label": "needs info",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25212#event-225933"
}
```



---

archive/issue_events_225934.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-07-18T11:47:03Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "milestone": "sage-8.3",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25212#event-225934"
}
```



---

archive/issue_events_225935.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-07-18T11:47:03Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "milestone": "sage-8.4",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25212#event-225935"
}
```



---

archive/issue_comments_388093.json:
```json
{
    "body": "<a id='comment:10'></a>\nI believe this issue can reasonably be addressed for Sage 8.4.",
    "created_at": "2018-07-18T11:47:03Z",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/25212#issuecomment-388093",
    "user": "https://github.com/embray"
}
```

<a id='comment:10'></a>
I believe this issue can reasonably be addressed for Sage 8.4.



---

archive/issue_comments_388094.json:
```json
{
    "body": "<a id='comment:11'></a>\nFixed in #26038.",
    "created_at": "2018-08-10T14:43:56Z",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/25212#issuecomment-388094",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:11'></a>
Fixed in #26038.



---

archive/issue_events_225936.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2018-08-10T14:43:56Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "label": "duplicate",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25212#event-225936"
}
```



---

archive/issue_events_225937.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2018-08-10T14:43:56Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "milestone": "sage-8.4",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25212#event-225937"
}
```



---

archive/issue_events_225938.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2018-08-10T14:43:56Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "label": "needs info",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25212#event-225938"
}
```



---

archive/issue_events_225939.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2018-08-10T14:43:56Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/25212",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25212#event-225939"
}
```
