# Issue 17797: random failure in cachefunc.pyx

archive/issues_017560.json:
```json
{
    "body": "This looks like an obvious thing to go wrong if the system load is only high enough: \n\n```\nsage -t --long --warn-long 66.4 src/sage/misc/cachefunc.pyx\n**********************************************************************\nFile \"src/sage/misc/cachefunc.pyx\", line 3408, in sage.misc.cachefunc.DiskCachedFunction.__init__\nFailed example:\n    walltime(w) < 2\nExpected:\n    True\nGot:\n    False\n**********************************************************************\n1 item had failures:\n   1 of   8 in sage.misc.cachefunc.DiskCachedFunction.__init__\n    [749 tests, 1 failure, 35.71 s]\n```\n\n**CC:**  @simon-king-jena\n\n**Keywords:** random_fail\n\nIssue created by migration from https://trac.sagemath.org/ticket/17797\n\n",
    "created_at": "2015-02-17T23:35:42Z",
    "labels": [
        "component: misc",
        "bug"
    ],
    "title": "random failure in cachefunc.pyx",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/17797",
    "user": "https://github.com/vbraun"
}
```
This looks like an obvious thing to go wrong if the system load is only high enough: 

```
sage -t --long --warn-long 66.4 src/sage/misc/cachefunc.pyx
**********************************************************************
File "src/sage/misc/cachefunc.pyx", line 3408, in sage.misc.cachefunc.DiskCachedFunction.__init__
Failed example:
    walltime(w) < 2
Expected:
    True
Got:
    False
**********************************************************************
1 item had failures:
   1 of   8 in sage.misc.cachefunc.DiskCachedFunction.__init__
    [749 tests, 1 failure, 35.71 s]
```

**CC:**  @simon-king-jena

**Keywords:** random_fail

Issue created by migration from https://trac.sagemath.org/ticket/17797





---

archive/issue_events_160919.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-12-29T01:31:15Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/17797",
    "milestone": "sage-6.6",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/17797#event-160919"
}
```
