# Issue 21914: Jupiter notebook prompts 404 GET

archive/issues_021677.json:
```json
{
    "body": "\n```\n[W 15:26:25.458 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20161121152618 (127.0.0.1) 15.66ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=sagemath\n```\n\nThis is version 7.3, and I run it using `sage -n jupyter` on ubuntu 14.04 with firefox.\n\n**Keywords:** js, days79, jupyter\n\nIssue created by migration from https://trac.sagemath.org/ticket/21914\n\n",
    "closed_at": "2017-04-19T09:27:37Z",
    "created_at": "2016-11-21T13:35:44Z",
    "labels": [
        "component: notebook",
        "minor",
        "bug",
        "worksforme",
        "invalid"
    ],
    "title": "Jupiter notebook prompts 404 GET",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/21914",
    "user": "https://github.com/pelegm"
}
```

```
[W 15:26:25.458 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20161121152618 (127.0.0.1) 15.66ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=sagemath
```

This is version 7.3, and I run it using `sage -n jupyter` on ubuntu 14.04 with firefox.

**Keywords:** js, days79, jupyter

Issue created by migration from https://trac.sagemath.org/ticket/21914





---

archive/issue_comments_325423.json:
```json
{
    "body": "**Changing keywords** from \"js\" to \"js, days79\".",
    "created_at": "2016-11-22T09:30:40Z",
    "issue": "https://github.com/sagemath/sage/issues/21914",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/21914#issuecomment-325423",
    "user": "https://github.com/pelegm"
}
```

**Changing keywords** from "js" to "js, days79".



---

archive/issue_comments_325424.json:
```json
{
    "body": "<a id='comment:2'></a>\nI don't see this error in 7.5.beta4 (still see it in 7.3).\n\nIn that case: should we close this ticket?",
    "created_at": "2016-11-27T20:34:08Z",
    "issue": "https://github.com/sagemath/sage/issues/21914",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/21914#issuecomment-325424",
    "user": "https://github.com/pelegm"
}
```

<a id='comment:2'></a>
I don't see this error in 7.5.beta4 (still see it in 7.3).

In that case: should we close this ticket?



---

archive/issue_comments_325425.json:
```json
{
    "body": "**Changing keywords** from \"js, days79\" to \"js, days79, jupyter\".",
    "created_at": "2016-11-27T20:34:08Z",
    "issue": "https://github.com/sagemath/sage/issues/21914",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/21914#issuecomment-325425",
    "user": "https://github.com/pelegm"
}
```

**Changing keywords** from "js, days79" to "js, days79, jupyter".



---

archive/issue_events_197829.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2017-04-19T09:27:37Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/21914",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/21914#event-197829"
}
```



---

archive/issue_events_197830.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2017-04-19T09:27:37Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/21914",
    "label": "worksforme",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/21914#event-197830"
}
```



---

archive/issue_events_197831.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2017-04-19T09:27:37Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/21914",
    "milestone": "sage-7.5",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/21914#event-197831"
}
```
