# Issue 34772: Test failure in `plot/plot.py` with specific random seed

archive/issues_034535.json:
```json
{
    "assignees": [],
    "body": "<div id=\"comment:0\"></div>\n\nOnly happens when testing with `--long` *and* using this specific random seed (even though the test itself is not tagged long and does not use any random data)\n\n```\nsage -t --long --random-seed=169929447503951982293191593843049330333 /usr/lib/python3.10/site-packages/sage/plot/plot.py\n**********************************************************************\nFile \"/usr/lib/python3.10/site-packages/sage/plot/plot.py\", line 1824, in sage.plot.plot.plot\nFailed example:\n    plot(f, (x, -3.5, 3.5), detect_poles='show', exclude=[-3..3], ymin=-5, ymax=5)\nExpected:\n    Graphics object consisting of 12 graphics primitives\nGot:\n    Graphics object consisting of 13 graphics primitives\n**********************************************************************\n```\n\nComponent: **graphics**\n\n_Issue created by migration from https://trac.sagemath.org/ticket/34772_\n\n",
    "created_at": "2022-11-22T17:35:55Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/c%3A%20graphics",
        "https://github.com/sagemath/sage/labels/p%3A%20major%20/%203",
        "https://github.com/sagemath/sage/labels/bug"
    ],
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "Test failure in `plot/plot.py` with specific random seed",
    "type": "issue",
    "updated_at": "2023-01-29T23:06:23Z",
    "url": "https://github.com/sagemath/sage/issues/34772",
    "user": "https://github.com/antonio-rojas"
}
```
<div id="comment:0"></div>

Only happens when testing with `--long` *and* using this specific random seed (even though the test itself is not tagged long and does not use any random data)

```
sage -t --long --random-seed=169929447503951982293191593843049330333 /usr/lib/python3.10/site-packages/sage/plot/plot.py
**********************************************************************
File "/usr/lib/python3.10/site-packages/sage/plot/plot.py", line 1824, in sage.plot.plot.plot
Failed example:
    plot(f, (x, -3.5, 3.5), detect_poles='show', exclude=[-3..3], ymin=-5, ymax=5)
Expected:
    Graphics object consisting of 12 graphics primitives
Got:
    Graphics object consisting of 13 graphics primitives
**********************************************************************
```

Component: **graphics**

_Issue created by migration from https://trac.sagemath.org/ticket/34772_





---

archive/issue_events_471651.json:
```json
{
    "actor": "https://github.com/antonio-rojas",
    "created_at": "2022-11-22T17:35:55Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/34772",
    "milestone_number": null,
    "milestone_title": "sage-9.8",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34772#event-471651"
}
```



---

archive/issue_events_471652.json:
```json
{
    "actor": "https://github.com/antonio-rojas",
    "created_at": "2022-11-22T17:35:55Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/34772",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20graphics",
    "label_color": "0000ff",
    "label_name": "c: graphics",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34772#event-471652"
}
```



---

archive/issue_events_471653.json:
```json
{
    "actor": "https://github.com/antonio-rojas",
    "created_at": "2022-11-22T17:35:55Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/34772",
    "label": "https://github.com/sagemath/sage/labels/p%3A%20major%20/%203",
    "label_color": "ffbb00",
    "label_name": "p: major / 3",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34772#event-471653"
}
```



---

archive/issue_events_471654.json:
```json
{
    "actor": "https://github.com/antonio-rojas",
    "created_at": "2022-11-22T17:35:55Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/34772",
    "label": "https://github.com/sagemath/sage/labels/bug",
    "label_color": "d73a4a",
    "label_name": "bug",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34772#event-471654"
}
```



---

archive/issue_events_471655.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2023-01-29T23:06:23Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/34772",
    "milestone_number": null,
    "milestone_title": "sage-9.8",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34772#event-471655"
}
```
