# Issue 34934: Elliptic curves isogeny:  test failing randomly

archive/issues_034697.json:
```json
{
    "assignees": [],
    "body": "<div id=\"comment:0\"></div>\n\nFor this particular seed, the following test\n\n```\nsage -t --long --warn-long 34.2 --random-seed=152197772011569013238342510928576188390 src/sage/schemes/elliptic_curves/ell_curve_isogeny.py\n```\nfails on [SageMath](../wiki/SageMath) 9.8.beta7 as follows:\n\n```\n**********************************************************************\nFile \"src/sage/schemes/elliptic_curves/ell_curve_isogeny.py\", line 2962, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual\nFailed example:\n    E.isogeny(3*E.lift_x(0)).dual()\nException raised:\n    Traceback (most recent call last):\n      File \"/Users/gms/SageMath/Git/sage/src/sage/doctest/forker.py\", line 695, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/Users/gms/SageMath/Git/sage/src/sage/doctest/forker.py\", line 1093, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual[38]>\", line 1, in <module>\n        E.isogeny(Integer(3)*E.lift_x(Integer(0))).dual()\n      File \"/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/ell_curve_isogeny.py\", line 3076, in dual\n        corr = find_post_isomorphism(mult, rhs)\n      File \"/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/hom.py\", line 856, in find_post_isomorphism\n        isos = [iso for iso in isos if iso._eval(im_phi) == im_psi]\n      File \"/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/hom.py\", line 856, in <listcomp>\n        isos = [iso for iso in isos if iso._eval(im_phi) == im_psi]\n      File \"/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/weierstrass_morphism.py\", line 586, in _eval\n        return self._codomain.base_extend(k).point(Q)\n      File \"/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/ell_generic.py\", line 1352, in base_extend\n        E = constructor.EllipticCurve([R(a) for a in self.a_invariants()])\n      File \"/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/ell_generic.py\", line 1352, in <listcomp>\n        E = constructor.EllipticCurve([R(a) for a in self.a_invariants()])\n      File \"sage/rings/finite_rings/element_givaro.pyx\", line 1355, in sage.rings.finite_rings.element_givaro.FiniteField_givaroElement.__int__\n        raise TypeError(\"Cannot coerce element to an integer.\")\n    TypeError: Cannot coerce element to an integer.\n**********************************************************************\n1 item had failures:\n   1 of  69 in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual\n    [871 tests, 1 failure, 8.94 s]\n----------------------------------------------------------------------\nsage -t --long --warn-long 34.2 --random-seed=152197772011569013238342510928576188390 src/sage/schemes/elliptic_curves/ell_curve_isogeny.py  # 1 doctest failed\n----------------------------------------------------------------------\n```\nI would be curious to know how (un)lucky I am...\n\nCC:  @yyyyx4\n\nComponent: **elliptic curves**\n\n_Issue created by migration from https://trac.sagemath.org/ticket/34934_\n\n",
    "created_at": "2023-01-24T20:52:10Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/c%3A%20elliptic%20curves",
        "https://github.com/sagemath/sage/labels/p%3A%20major%20/%203",
        "https://github.com/sagemath/sage/labels/bug"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-9.8",
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "Elliptic curves isogeny:  test failing randomly",
    "type": "issue",
    "updated_at": "2023-01-25T09:21:05Z",
    "url": "https://github.com/sagemath/sage/issues/34934",
    "user": "https://github.com/GMS103"
}
```
<div id="comment:0"></div>

For this particular seed, the following test

```
sage -t --long --warn-long 34.2 --random-seed=152197772011569013238342510928576188390 src/sage/schemes/elliptic_curves/ell_curve_isogeny.py
```
fails on [SageMath](../wiki/SageMath) 9.8.beta7 as follows:

```
**********************************************************************
File "src/sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 2962, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual
Failed example:
    E.isogeny(3*E.lift_x(0)).dual()
Exception raised:
    Traceback (most recent call last):
      File "/Users/gms/SageMath/Git/sage/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/gms/SageMath/Git/sage/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual[38]>", line 1, in <module>
        E.isogeny(Integer(3)*E.lift_x(Integer(0))).dual()
      File "/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 3076, in dual
        corr = find_post_isomorphism(mult, rhs)
      File "/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/hom.py", line 856, in find_post_isomorphism
        isos = [iso for iso in isos if iso._eval(im_phi) == im_psi]
      File "/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/hom.py", line 856, in <listcomp>
        isos = [iso for iso in isos if iso._eval(im_phi) == im_psi]
      File "/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/weierstrass_morphism.py", line 586, in _eval
        return self._codomain.base_extend(k).point(Q)
      File "/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/ell_generic.py", line 1352, in base_extend
        E = constructor.EllipticCurve([R(a) for a in self.a_invariants()])
      File "/Users/gms/SageMath/Git/sage/src/sage/schemes/elliptic_curves/ell_generic.py", line 1352, in <listcomp>
        E = constructor.EllipticCurve([R(a) for a in self.a_invariants()])
      File "sage/rings/finite_rings/element_givaro.pyx", line 1355, in sage.rings.finite_rings.element_givaro.FiniteField_givaroElement.__int__
        raise TypeError("Cannot coerce element to an integer.")
    TypeError: Cannot coerce element to an integer.
**********************************************************************
1 item had failures:
   1 of  69 in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual
    [871 tests, 1 failure, 8.94 s]
----------------------------------------------------------------------
sage -t --long --warn-long 34.2 --random-seed=152197772011569013238342510928576188390 src/sage/schemes/elliptic_curves/ell_curve_isogeny.py  # 1 doctest failed
----------------------------------------------------------------------
```
I would be curious to know how (un)lucky I am...

CC:  @yyyyx4

Component: **elliptic curves**

_Issue created by migration from https://trac.sagemath.org/ticket/34934_





---

archive/issue_events_473010.json:
```json
{
    "actor": "https://github.com/GMS103",
    "created_at": "2023-01-24T20:52:10Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/34934",
    "milestone_number": null,
    "milestone_title": "sage-9.8",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34934#event-473010"
}
```



---

archive/issue_events_473011.json:
```json
{
    "actor": "https://github.com/GMS103",
    "created_at": "2023-01-24T20:52:10Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/34934",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20elliptic%20curves",
    "label_color": "0000ff",
    "label_name": "c: elliptic curves",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34934#event-473011"
}
```



---

archive/issue_events_473012.json:
```json
{
    "actor": "https://github.com/GMS103",
    "created_at": "2023-01-24T20:52:10Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/34934",
    "label": "https://github.com/sagemath/sage/labels/p%3A%20major%20/%203",
    "label_color": "ffbb00",
    "label_name": "p: major / 3",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34934#event-473012"
}
```



---

archive/issue_events_473013.json:
```json
{
    "actor": "https://github.com/GMS103",
    "created_at": "2023-01-24T20:52:10Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/34934",
    "label": "https://github.com/sagemath/sage/labels/bug",
    "label_color": "d73a4a",
    "label_name": "bug",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34934#event-473013"
}
```



---

archive/issue_comments_562725.json:
```json
{
    "body": "Description changed:\n``````diff\n--- \n+++ \n@@ -41,139 +41,4 @@\n sage -t --long --warn-long 34.2 --random-seed=152197772011569013238342510928576188390 src/sage/schemes/elliptic_curves/ell_curve_isogeny.py  # 1 doctest failed\n ----------------------------------------------------------------------\n ```\n-It also fails on [SageMath](../wiki/SageMath) 9.7, but in a different way:\n-\n-```\n-**********************************************************************\n-File \"src/sage/schemes/elliptic_curves/ell_curve_isogeny.py\", line 824, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny\n-Failed example:\n-    phi2 = phi * phi; phi2\n-Expected:\n-    Composite morphism of degree 9 = 3^2:\n-      From: Elliptic Curve defined by y^2 = x^3 + 1 over Finite Field of size 7\n-      To:   Elliptic Curve defined by y^2 = x^3 + 1 over Finite Field of size 7\n-Got:\n-    Composite map:\n-      From: Elliptic Curve defined by y^2 = x^3 + 1 over Finite Field of size 7\n-      To:   Elliptic Curve defined by y^2 = x^3 + 1 over Finite Field of size 7\n-      Defn:   Isogeny of degree 3 from Elliptic Curve defined by y^2 = x^3 + 1 over Finite Field of size 7 to Elliptic Curve defined by y^2 = x^3 + 1 over Finite Field of size 7\n-            then\n-              Isogeny of degree 3 from Elliptic Curve defined by y^2 = x^3 + 1 over Finite Field of size 7 to Elliptic Curve defined by y^2 = x^3 + 1 over Finite Field of size 7\n-**********************************************************************\n-File \"src/sage/schemes/elliptic_curves/ell_curve_isogeny.py\", line 1163, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny._call_\n-Failed example:\n-    phi(Q)._order\n-Exception raised:\n-    Traceback (most recent call last):\n-      File \"/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py\", line 695, in _run\n-        self.compile_and_execute(example, compiler, test.globs)\n-      File \"/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py\", line 1093, in compile_and_execute\n-        exec(compiled, globs)\n-      File \"<doctest sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny._call_[39]>\", line 1, in <module>\n-        phi(Q)._order\n-      File \"sage/structure/element.pyx\", line 494, in sage.structure.element.Element.__getattr__ (build/cythonized/sage/structure/element.c:4884)\n-        return self.getattr_from_category(name)\n-      File \"sage/structure/element.pyx\", line 507, in sage.structure.element.Element.getattr_from_category (build/cythonized/sage/structure/element.c:4996)\n-        return getattr_from_other_class(self, cls, name)\n-      File \"sage/cpython/getattr.pyx\", line 361, in sage.cpython.getattr.getattr_from_other_class (build/cythonized/sage/cpython/getattr.c:2773)\n-        raise AttributeError(dummy_error_message)\n-    AttributeError: 'EllipticCurvePoint_finite_field' object has no attribute '_order'\n-**********************************************************************\n-File \"src/sage/schemes/elliptic_curves/ell_curve_isogeny.py\", line 1404, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.__clear_cached_values\n-Failed example:\n-    from sage.schemes.elliptic_curves.weierstrass_morphism import negation_morphism\n-Exception raised:\n-    Traceback (most recent call last):\n-      File \"/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py\", line 695, in _run\n-        self.compile_and_execute(example, compiler, test.globs)\n-      File \"/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py\", line 1093, in compile_and_execute\n-        exec(compiled, globs)\n-      File \"<doctest sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.__clear_cached_values[4]>\", line 1, in <module>\n-        from sage.schemes.elliptic_curves.weierstrass_morphism import negation_morphism\n-    ImportError: cannot import name 'negation_morphism' from 'sage.schemes.elliptic_curves.weierstrass_morphism' (/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/schemes/elliptic_curves/weierstrass_morphism.py)\n-**********************************************************************\n-File \"src/sage/schemes/elliptic_curves/ell_curve_isogeny.py\", line 1405, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.__clear_cached_values\n-Failed example:\n-    phi._set_post_isomorphism(negation_morphism(phi.codomain()))\n-Exception raised:\n-    Traceback (most recent call last):\n-      File \"/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py\", line 695, in _run\n-        self.compile_and_execute(example, compiler, test.globs)\n-      File \"/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py\", line 1093, in compile_and_execute\n-        exec(compiled, globs)\n-      File \"<doctest sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.__clear_cached_values[5]>\", line 1, in <module>\n-        phi._set_post_isomorphism(negation_morphism(phi.codomain()))\n-    NameError: name 'negation_morphism' is not defined\n-**********************************************************************\n-File \"src/sage/schemes/elliptic_curves/ell_curve_isogeny.py\", line 1406, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.__clear_cached_values\n-Failed example:\n-    old_ratl_maps == phi.rational_maps()\n-Expected:\n-    False\n-Got:\n-    True\n-**********************************************************************\n-File \"src/sage/schemes/elliptic_curves/ell_curve_isogeny.py\", line 1408, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.__clear_cached_values\n-Failed example:\n-    old_ratl_maps[1] == -phi.rational_maps()[1]\n-Expected:\n-    True\n-Got:\n-    False\n-**********************************************************************\n-File \"src/sage/schemes/elliptic_curves/ell_curve_isogeny.py\", line 2962, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual\n-Failed example:\n-    E.isogeny(3*E.lift_x(0)).dual()\n-Exception raised:\n-    Traceback (most recent call last):\n-      File \"/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py\", line 695, in _run\n-        self.compile_and_execute(example, compiler, test.globs)\n-      File \"/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py\", line 1093, in compile_and_execute\n-        exec(compiled, globs)\n-      File \"<doctest sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual[38]>\", line 1, in <module>\n-        E.isogeny(Integer(3)*E.lift_x(Integer(0))).dual()\n-      File \"/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/schemes/elliptic_curves/ell_curve_isogeny.py\", line 3248, in dual\n-        raise NotImplementedError(\"the dual isogeny is not separable: only separable isogenies are currently implemented\")\n-    NotImplementedError: the dual isogeny is not separable: only separable isogenies are currently implemented\n-**********************************************************************\n-File \"src/sage/schemes/elliptic_curves/ell_curve_isogeny.py\", line 2966, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual\n-Failed example:\n-    E.isogeny(E.lift_x(0)).dual()\n-Exception raised:\n-    Traceback (most recent call last):\n-      File \"/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py\", line 695, in _run\n-        self.compile_and_execute(example, compiler, test.globs)\n-      File \"/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py\", line 1093, in compile_and_execute\n-        exec(compiled, globs)\n-      File \"<doctest sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual[39]>\", line 1, in <module>\n-        E.isogeny(E.lift_x(Integer(0))).dual()\n-      File \"/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/schemes/elliptic_curves/ell_curve_isogeny.py\", line 3248, in dual\n-        raise NotImplementedError(\"the dual isogeny is not separable: only separable isogenies are currently implemented\")\n-    NotImplementedError: the dual isogeny is not separable: only separable isogenies are currently implemented\n-**********************************************************************\n-File \"src/sage/schemes/elliptic_curves/ell_curve_isogeny.py\", line 2978, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual\n-Failed example:\n-    phi.dual()\n-Exception raised:\n-    Traceback (most recent call last):\n-      File \"/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py\", line 695, in _run\n-        self.compile_and_execute(example, compiler, test.globs)\n-      File \"/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py\", line 1093, in compile_and_execute\n-        exec(compiled, globs)\n-      File \"<doctest sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual[45]>\", line 1, in <module>\n-        phi.dual()\n-      File \"/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/schemes/elliptic_curves/ell_curve_isogeny.py\", line 3248, in dual\n-        raise NotImplementedError(\"the dual isogeny is not separable: only separable isogenies are currently implemented\")\n-    NotImplementedError: the dual isogeny is not separable: only separable isogenies are currently implemented\n-**********************************************************************\n-4 items had failures:\n-   1 of 135 in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny\n-   4 of  18 in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.__clear_cached_values\n-   1 of  41 in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny._call_\n-   3 of  69 in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual\n-    [871 tests, 9 failures, 8.34 s]\n-----------------------------------------------------------------------\n-sage -t --long --warn-long 34.2 --random-seed=152197772011569013238342510928576188390 src/sage/schemes/elliptic_curves/ell_curve_isogeny.py  # 9 doctests failed\n-----------------------------------------------------------------------\n-```\n I would be curious to know how (un)lucky I am...\n``````\n",
    "created_at": "2023-01-24T21:31:17Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/34934",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/34934#issuecomment-562725",
    "user": "https://github.com/GMS103"
}
```

Description changed:
``````diff
--- 
+++ 
@@ -41,139 +41,4 @@
 sage -t --long --warn-long 34.2 --random-seed=152197772011569013238342510928576188390 src/sage/schemes/elliptic_curves/ell_curve_isogeny.py  # 1 doctest failed
 ----------------------------------------------------------------------
 ```
-It also fails on [SageMath](../wiki/SageMath) 9.7, but in a different way:
-
-```
-**********************************************************************
-File "src/sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 824, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny
-Failed example:
-    phi2 = phi * phi; phi2
-Expected:
-    Composite morphism of degree 9 = 3^2:
-      From: Elliptic Curve defined by y^2 = x^3 + 1 over Finite Field of size 7
-      To:   Elliptic Curve defined by y^2 = x^3 + 1 over Finite Field of size 7
-Got:
-    Composite map:
-      From: Elliptic Curve defined by y^2 = x^3 + 1 over Finite Field of size 7
-      To:   Elliptic Curve defined by y^2 = x^3 + 1 over Finite Field of size 7
-      Defn:   Isogeny of degree 3 from Elliptic Curve defined by y^2 = x^3 + 1 over Finite Field of size 7 to Elliptic Curve defined by y^2 = x^3 + 1 over Finite Field of size 7
-            then
-              Isogeny of degree 3 from Elliptic Curve defined by y^2 = x^3 + 1 over Finite Field of size 7 to Elliptic Curve defined by y^2 = x^3 + 1 over Finite Field of size 7
-**********************************************************************
-File "src/sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 1163, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny._call_
-Failed example:
-    phi(Q)._order
-Exception raised:
-    Traceback (most recent call last):
-      File "/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py", line 695, in _run
-        self.compile_and_execute(example, compiler, test.globs)
-      File "/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py", line 1093, in compile_and_execute
-        exec(compiled, globs)
-      File "<doctest sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny._call_[39]>", line 1, in <module>
-        phi(Q)._order
-      File "sage/structure/element.pyx", line 494, in sage.structure.element.Element.__getattr__ (build/cythonized/sage/structure/element.c:4884)
-        return self.getattr_from_category(name)
-      File "sage/structure/element.pyx", line 507, in sage.structure.element.Element.getattr_from_category (build/cythonized/sage/structure/element.c:4996)
-        return getattr_from_other_class(self, cls, name)
-      File "sage/cpython/getattr.pyx", line 361, in sage.cpython.getattr.getattr_from_other_class (build/cythonized/sage/cpython/getattr.c:2773)
-        raise AttributeError(dummy_error_message)
-    AttributeError: 'EllipticCurvePoint_finite_field' object has no attribute '_order'
-**********************************************************************
-File "src/sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 1404, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.__clear_cached_values
-Failed example:
-    from sage.schemes.elliptic_curves.weierstrass_morphism import negation_morphism
-Exception raised:
-    Traceback (most recent call last):
-      File "/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py", line 695, in _run
-        self.compile_and_execute(example, compiler, test.globs)
-      File "/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py", line 1093, in compile_and_execute
-        exec(compiled, globs)
-      File "<doctest sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.__clear_cached_values[4]>", line 1, in <module>
-        from sage.schemes.elliptic_curves.weierstrass_morphism import negation_morphism
-    ImportError: cannot import name 'negation_morphism' from 'sage.schemes.elliptic_curves.weierstrass_morphism' (/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/schemes/elliptic_curves/weierstrass_morphism.py)
-**********************************************************************
-File "src/sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 1405, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.__clear_cached_values
-Failed example:
-    phi._set_post_isomorphism(negation_morphism(phi.codomain()))
-Exception raised:
-    Traceback (most recent call last):
-      File "/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py", line 695, in _run
-        self.compile_and_execute(example, compiler, test.globs)
-      File "/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py", line 1093, in compile_and_execute
-        exec(compiled, globs)
-      File "<doctest sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.__clear_cached_values[5]>", line 1, in <module>
-        phi._set_post_isomorphism(negation_morphism(phi.codomain()))
-    NameError: name 'negation_morphism' is not defined
-**********************************************************************
-File "src/sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 1406, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.__clear_cached_values
-Failed example:
-    old_ratl_maps == phi.rational_maps()
-Expected:
-    False
-Got:
-    True
-**********************************************************************
-File "src/sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 1408, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.__clear_cached_values
-Failed example:
-    old_ratl_maps[1] == -phi.rational_maps()[1]
-Expected:
-    True
-Got:
-    False
-**********************************************************************
-File "src/sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 2962, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual
-Failed example:
-    E.isogeny(3*E.lift_x(0)).dual()
-Exception raised:
-    Traceback (most recent call last):
-      File "/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py", line 695, in _run
-        self.compile_and_execute(example, compiler, test.globs)
-      File "/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py", line 1093, in compile_and_execute
-        exec(compiled, globs)
-      File "<doctest sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual[38]>", line 1, in <module>
-        E.isogeny(Integer(3)*E.lift_x(Integer(0))).dual()
-      File "/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 3248, in dual
-        raise NotImplementedError("the dual isogeny is not separable: only separable isogenies are currently implemented")
-    NotImplementedError: the dual isogeny is not separable: only separable isogenies are currently implemented
-**********************************************************************
-File "src/sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 2966, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual
-Failed example:
-    E.isogeny(E.lift_x(0)).dual()
-Exception raised:
-    Traceback (most recent call last):
-      File "/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py", line 695, in _run
-        self.compile_and_execute(example, compiler, test.globs)
-      File "/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py", line 1093, in compile_and_execute
-        exec(compiled, globs)
-      File "<doctest sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual[39]>", line 1, in <module>
-        E.isogeny(E.lift_x(Integer(0))).dual()
-      File "/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 3248, in dual
-        raise NotImplementedError("the dual isogeny is not separable: only separable isogenies are currently implemented")
-    NotImplementedError: the dual isogeny is not separable: only separable isogenies are currently implemented
-**********************************************************************
-File "src/sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 2978, in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual
-Failed example:
-    phi.dual()
-Exception raised:
-    Traceback (most recent call last):
-      File "/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py", line 695, in _run
-        self.compile_and_execute(example, compiler, test.globs)
-      File "/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/doctest/forker.py", line 1093, in compile_and_execute
-        exec(compiled, globs)
-      File "<doctest sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual[45]>", line 1, in <module>
-        phi.dual()
-      File "/private/var/tmp/sage-9.7-current/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/sage/schemes/elliptic_curves/ell_curve_isogeny.py", line 3248, in dual
-        raise NotImplementedError("the dual isogeny is not separable: only separable isogenies are currently implemented")
-    NotImplementedError: the dual isogeny is not separable: only separable isogenies are currently implemented
-**********************************************************************
-4 items had failures:
-   1 of 135 in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny
-   4 of  18 in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.__clear_cached_values
-   1 of  41 in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny._call_
-   3 of  69 in sage.schemes.elliptic_curves.ell_curve_isogeny.EllipticCurveIsogeny.dual
-    [871 tests, 9 failures, 8.34 s]
-----------------------------------------------------------------------
-sage -t --long --warn-long 34.2 --random-seed=152197772011569013238342510928576188390 src/sage/schemes/elliptic_curves/ell_curve_isogeny.py  # 9 doctests failed
-----------------------------------------------------------------------
-```
 I would be curious to know how (un)lucky I am...
``````

