# Issue 29551: bug in computing automorphism group of IncidenceStructure

archive/issues_029314.json:
```json
{
    "assignees": [],
    "body": "<div id=\"comment:0\"></div>\n\nFrom sage-devel thread\n\n```\nB = [[1, 2, 3, 5, 7, 10],\n [1, 2, 3, 7, 10, 11],\n [1, 2, 4, 6, 9, 10],\n [1, 2, 4, 7, 8, 10],\n [1, 2, 5, 6, 10, 11],\n [1, 2, 7, 8, 9, 10],\n [2, 3, 4, 5, 9, 10],\n [2, 3, 4, 9, 10, 11],\n [2, 4, 5, 8, 10, 11],\n [2, 4, 6, 7, 9, 10],\n [2, 5, 6, 7, 10, 11],\n [2, 5, 8, 9, 10, 11]]\nC = B + [[1..11]]\nI1 = IncidenceStructure([1..11],B)\nI2 = IncidenceStructure([1..11],C)\nA1 = I1.automorphism_group()\nA2 = I2.automorphism_group()\nA1.order()==A2.order()\n```\nreturs false - the group orders are 96 and 32, rather than equal to 96.\nThis still is correct (same group) in Sage 8.9 with Python 2, but wrong in 9.1.rc0 as well as in 9.0 (with Python 3).\n\n\n\n\nCC:  @dcoudert\n\nComponent: **graph theory**\n\n_Issue created by migration from https://trac.sagemath.org/ticket/29551_\n\n",
    "created_at": "2020-04-23T04:21:05Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/c%3A%20graph%20theory",
        "https://github.com/sagemath/sage/labels/p%3A%20critical%20/%202",
        "https://github.com/sagemath/sage/labels/bug"
    ],
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "bug in computing automorphism group of IncidenceStructure",
    "type": "issue",
    "updated_at": "2023-01-29T23:06:23Z",
    "url": "https://github.com/sagemath/sage/issues/29551",
    "user": "https://github.com/dimpase"
}
```
<div id="comment:0"></div>

From sage-devel thread

```
B = [[1, 2, 3, 5, 7, 10],
 [1, 2, 3, 7, 10, 11],
 [1, 2, 4, 6, 9, 10],
 [1, 2, 4, 7, 8, 10],
 [1, 2, 5, 6, 10, 11],
 [1, 2, 7, 8, 9, 10],
 [2, 3, 4, 5, 9, 10],
 [2, 3, 4, 9, 10, 11],
 [2, 4, 5, 8, 10, 11],
 [2, 4, 6, 7, 9, 10],
 [2, 5, 6, 7, 10, 11],
 [2, 5, 8, 9, 10, 11]]
C = B + [[1..11]]
I1 = IncidenceStructure([1..11],B)
I2 = IncidenceStructure([1..11],C)
A1 = I1.automorphism_group()
A2 = I2.automorphism_group()
A1.order()==A2.order()
```
returs false - the group orders are 96 and 32, rather than equal to 96.
This still is correct (same group) in Sage 8.9 with Python 2, but wrong in 9.1.rc0 as well as in 9.0 (with Python 3).




CC:  @dcoudert

Component: **graph theory**

_Issue created by migration from https://trac.sagemath.org/ticket/29551_





---

archive/issue_events_403913.json:
```json
{
    "actor": "https://github.com/dimpase",
    "created_at": "2020-04-23T04:21:05Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "milestone_number": null,
    "milestone_title": "sage-9.1",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403913"
}
```



---

archive/issue_events_403914.json:
```json
{
    "actor": "https://github.com/dimpase",
    "created_at": "2020-04-23T04:21:05Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20graph%20theory",
    "label_color": "0000ff",
    "label_name": "c: graph theory",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403914"
}
```



---

archive/issue_events_403915.json:
```json
{
    "actor": "https://github.com/dimpase",
    "created_at": "2020-04-23T04:21:05Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "label": "https://github.com/sagemath/sage/labels/p%3A%20critical%20/%202",
    "label_color": "ff7700",
    "label_name": "p: critical / 2",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403915"
}
```



---

archive/issue_events_403916.json:
```json
{
    "actor": "https://github.com/dimpase",
    "created_at": "2020-04-23T04:21:05Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "label": "https://github.com/sagemath/sage/labels/bug",
    "label_color": "d73a4a",
    "label_name": "bug",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403916"
}
```



---

archive/issue_comments_464870.json:
```json
{
    "body": "<div id=\"comment:1\" align=\"right\">comment:1</div>\n\nCan it not be possible that the case is like a particular nuance? because as reported by the user in Sage-Devel, the results were accurate for the other test cases?\np.s : Just an observation, nevertheless, it needs to be fixed",
    "created_at": "2020-04-23T05:24:16Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29551#issuecomment-464870",
    "user": "https://github.com/Shlokatadistance"
}
```

<div id="comment:1" align="right">comment:1</div>

Can it not be possible that the case is like a particular nuance? because as reported by the user in Sage-Devel, the results were accurate for the other test cases?
p.s : Just an observation, nevertheless, it needs to be fixed



---

archive/issue_comments_464871.json:
```json
{
    "body": "<div id=\"comment:2\" align=\"right\">comment:2</div>\n\nit is indeed a corner case, as the \"full\" block, as added in C, is not usual. If you want to fix this, look at the code of IncidenceStructure and check that the automorphism group of the incidence graph constructed there is not correct, for some reason.",
    "created_at": "2020-04-23T05:47:51Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29551#issuecomment-464871",
    "user": "https://github.com/dimpase"
}
```

<div id="comment:2" align="right">comment:2</div>

it is indeed a corner case, as the "full" block, as added in C, is not usual. If you want to fix this, look at the code of IncidenceStructure and check that the automorphism group of the incidence graph constructed there is not correct, for some reason.



---

archive/issue_comments_464872.json:
```json
{
    "body": "<div id=\"comment:3\" align=\"right\">comment:3</div>\n\nI could reproduce the bug with version 9.1.rc0 under Python 2 and on a stable 8.1, too. So it seemes, that it is older than 8.9 but disappeared for a while.",
    "created_at": "2020-04-24T07:19:57Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29551#issuecomment-464872",
    "user": "https://github.com/soehms"
}
```

<div id="comment:3" align="right">comment:3</div>

I could reproduce the bug with version 9.1.rc0 under Python 2 and on a stable 8.1, too. So it seemes, that it is older than 8.9 but disappeared for a while.



---

archive/issue_comments_464873.json:
```json
{
    "body": "<div id=\"comment:4\" align=\"right\">comment:4</div>\n\nI am trying to come up with a fix, but can someone suggest a few more test cases? Especially since we think this is a potential corner case, I dont want to suggest a fix which will output the wrong answer for the other right ones",
    "created_at": "2020-04-26T11:25:30Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29551#issuecomment-464873",
    "user": "https://github.com/Shlokatadistance"
}
```

<div id="comment:4" align="right">comment:4</div>

I am trying to come up with a fix, but can someone suggest a few more test cases? Especially since we think this is a potential corner case, I dont want to suggest a fix which will output the wrong answer for the other right ones



---

archive/issue_events_403917.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-05-07T02:29:39Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "milestone_number": null,
    "milestone_title": "sage-9.1",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403917"
}
```



---

archive/issue_events_403918.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-05-07T02:29:39Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "milestone_number": null,
    "milestone_title": "sage-9.2",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403918"
}
```



---

archive/issue_comments_464874.json:
```json
{
    "body": "<div id=\"comment:6\" align=\"right\">comment:6</div>\n\nPossibly related: #30637. Does your fix also solve that?",
    "created_at": "2020-09-24T10:05:51Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29551#issuecomment-464874",
    "user": "https://github.com/slel"
}
```

<div id="comment:6" align="right">comment:6</div>

Possibly related: #30637. Does your fix also solve that?



---

archive/issue_comments_464875.json:
```json
{
    "body": "<div id=\"comment:7\" align=\"right\">comment:7</div>\n\nI think this bug is located in `search_tree` (`sage.groups.perm_gps.partn_ref.refinement_graphs`) since with optional package `bliss` installed it is not reproducible.\n\nSamuel, does #30637 fail with `bliss`, as well?",
    "created_at": "2020-09-26T15:33:38Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29551#issuecomment-464875",
    "user": "https://github.com/soehms"
}
```

<div id="comment:7" align="right">comment:7</div>

I think this bug is located in `search_tree` (`sage.groups.perm_gps.partn_ref.refinement_graphs`) since with optional package `bliss` installed it is not reproducible.

Samuel, does #30637 fail with `bliss`, as well?



---

archive/issue_comments_464876.json:
```json
{
    "body": "<div id=\"comment:8\" align=\"right\">comment:8</div>\n\nI can confirm that after installing bliss, the issue here goes away.",
    "created_at": "2020-09-28T16:13:26Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29551#issuecomment-464876",
    "user": "https://github.com/dimpase"
}
```

<div id="comment:8" align="right">comment:8</div>

I can confirm that after installing bliss, the issue here goes away.



---

archive/issue_comments_464877.json:
```json
{
    "body": "<div id=\"comment:9\" align=\"right\">comment:9</div>\n\nby the way, without (and with) bliss, still\n\n```\nsage: g1=I1.incidence_graph()                                                                                                                                           \nsage: g2=I2.incidence_graph()                                                                                                                                           \nsage: g1.automorphism_group().order()                                                                                                                                   \n96\nsage: g2.automorphism_group().order()                                                                                                                                   \n96\n```\nare correct. As well, wihout bliss,\n\n```\nsage: I2.dual().automorphism_group().order()                                                                                                                            \n48\nsage: I1.dual().automorphism_group().order()                                                                                                                            \n48\n```\nwhich is consistent with 96/2=48 (there are two points, 2  and 10, which are in all the blocks, so there is an order two automorhism (2,10) fixing all blocks).",
    "created_at": "2020-09-28T17:40:50Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29551#issuecomment-464877",
    "user": "https://github.com/dimpase"
}
```

<div id="comment:9" align="right">comment:9</div>

by the way, without (and with) bliss, still

```
sage: g1=I1.incidence_graph()                                                                                                                                           
sage: g2=I2.incidence_graph()                                                                                                                                           
sage: g1.automorphism_group().order()                                                                                                                                   
96
sage: g2.automorphism_group().order()                                                                                                                                   
96
```
are correct. As well, wihout bliss,

```
sage: I2.dual().automorphism_group().order()                                                                                                                            
48
sage: I1.dual().automorphism_group().order()                                                                                                                            
48
```
which is consistent with 96/2=48 (there are two points, 2  and 10, which are in all the blocks, so there is an order two automorhism (2,10) fixing all blocks).



---

archive/issue_comments_464878.json:
```json
{
    "body": "Description changed:\n``````diff\n--- \n+++ \n@@ -20,7 +20,7 @@\n A2 = I2.automorphism_group()\n A1.order()==A2.order()\n ```\n-returs false - the group orders are 96 and 32, rather than equal.\n+returs false - the group orders are 96 and 32, rather than equal to 96.\n This still is correct (same group) in Sage 8.9 with Python 2, but wrong in 9.1.rc0 as well as in 9.0 (with Python 3).\n \n \n``````\n",
    "created_at": "2020-09-28T17:40:50Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29551#issuecomment-464878",
    "user": "https://github.com/dimpase"
}
```

Description changed:
``````diff
--- 
+++ 
@@ -20,7 +20,7 @@
 A2 = I2.automorphism_group()
 A1.order()==A2.order()
 ```
-returs false - the group orders are 96 and 32, rather than equal.
+returs false - the group orders are 96 and 32, rather than equal to 96.
 This still is correct (same group) in Sage 8.9 with Python 2, but wrong in 9.1.rc0 as well as in 9.0 (with Python 3).
 
 
``````




---

archive/issue_events_403919.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-10-24T20:15:01Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "milestone_number": null,
    "milestone_title": "sage-9.2",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403919"
}
```



---

archive/issue_events_403920.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-10-24T20:15:01Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "milestone_number": null,
    "milestone_title": "sage-9.3",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403920"
}
```



---

archive/issue_events_403921.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2021-05-10T17:42:09Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "milestone_number": null,
    "milestone_title": "sage-9.3",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403921"
}
```



---

archive/issue_events_403922.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2021-05-10T17:42:09Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "milestone_number": null,
    "milestone_title": "sage-9.4",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403922"
}
```



---

archive/issue_comments_464879.json:
```json
{
    "body": "<div id=\"comment:11\" align=\"right\">comment:11</div>\n\nMoving to 9.4, as 9.3 has been released.",
    "created_at": "2021-05-10T17:42:09Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29551#issuecomment-464879",
    "user": "https://github.com/mkoeppe"
}
```

<div id="comment:11" align="right">comment:11</div>

Moving to 9.4, as 9.3 has been released.



---

archive/issue_events_403923.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2021-08-22T20:35:10Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "milestone_number": null,
    "milestone_title": "sage-9.4",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403923"
}
```



---

archive/issue_events_403924.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2021-08-22T20:35:10Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "milestone_number": null,
    "milestone_title": "sage-9.5",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403924"
}
```



---

archive/issue_comments_464880.json:
```json
{
    "body": "<div id=\"comment:13\" align=\"right\">comment:13</div>\n\nbump to 9.6",
    "created_at": "2022-01-29T08:58:50Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29551#issuecomment-464880",
    "user": "https://github.com/fchapoton"
}
```

<div id="comment:13" align="right">comment:13</div>

bump to 9.6



---

archive/issue_events_403925.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2022-01-29T08:58:50Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "milestone_number": null,
    "milestone_title": "sage-9.5",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403925"
}
```



---

archive/issue_events_403926.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2022-01-29T08:58:50Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "milestone_number": null,
    "milestone_title": "sage-9.6",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403926"
}
```



---

archive/issue_events_403927.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-05-03T15:17:06Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "milestone_number": null,
    "milestone_title": "sage-9.6",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403927"
}
```



---

archive/issue_events_403928.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-05-03T15:17:06Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "milestone_number": null,
    "milestone_title": "sage-9.7",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403928"
}
```



---

archive/issue_events_403929.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-09-19T18:58:47Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "milestone_number": null,
    "milestone_title": "sage-9.7",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403929"
}
```



---

archive/issue_events_403930.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-09-19T18:58:47Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "milestone_number": null,
    "milestone_title": "sage-9.8",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403930"
}
```



---

archive/issue_events_403931.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2023-01-29T23:06:23Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/29551",
    "milestone_number": null,
    "milestone_title": "sage-9.8",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29551#event-403931"
}
```
