# Issue 33229: Reed Mueller code crashing

archive/issues_032992.json:
```json
{
    "assignees": [],
    "body": "<div id=\"comment:0\"></div>\n\nIn Sage 9.5.rc1, the following command causes a crash:\n\n```\nsage: C = codes.BinaryReedMullerCode(16, 32)\n------------------------------------------------------------------------\n(no backtrace available)\n------------------------------------------------------------------------\nUnhandled SIGSEGV: A segmentation fault occurred.\nThis probably occurred because a *compiled* module has a bug\nin it and is not properly wrapped with sig_on(), sig_off().\nPython will now terminate.\n------------------------------------------------------------------------\n.../src/bin/sage-python: line 2: 60716 Segmentation fault: 11  sage -python \"$@\"\n```\n\nIn case the input is invalid, an error\nwould be preferable to a crash.\n\n\nCC:  @slel\n\nComponent: **coding theory**\n\nKeywords: **segfault**\n\n_Issue created by migration from https://trac.sagemath.org/ticket/33229_\n\n",
    "created_at": "2022-01-25T08:52:01Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/c%3A%20coding%20theory",
        "https://github.com/sagemath/sage/labels/p%3A%20major%20/%203",
        "https://github.com/sagemath/sage/labels/bug"
    ],
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "Reed Mueller code crashing",
    "type": "issue",
    "updated_at": "2023-01-29T23:06:23Z",
    "url": "https://github.com/sagemath/sage/issues/33229",
    "user": "https://github.com/MathieuDutSik"
}
```
<div id="comment:0"></div>

In Sage 9.5.rc1, the following command causes a crash:

```
sage: C = codes.BinaryReedMullerCode(16, 32)
------------------------------------------------------------------------
(no backtrace available)
------------------------------------------------------------------------
Unhandled SIGSEGV: A segmentation fault occurred.
This probably occurred because a *compiled* module has a bug
in it and is not properly wrapped with sig_on(), sig_off().
Python will now terminate.
------------------------------------------------------------------------
.../src/bin/sage-python: line 2: 60716 Segmentation fault: 11  sage -python "$@"
```

In case the input is invalid, an error
would be preferable to a crash.


CC:  @slel

Component: **coding theory**

Keywords: **segfault**

_Issue created by migration from https://trac.sagemath.org/ticket/33229_





---

archive/issue_events_454929.json:
```json
{
    "actor": "https://github.com/MathieuDutSik",
    "created_at": "2022-01-25T08:52:01Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/33229",
    "milestone_number": null,
    "milestone_title": "sage-9.6",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33229#event-454929"
}
```



---

archive/issue_events_454930.json:
```json
{
    "actor": "https://github.com/MathieuDutSik",
    "created_at": "2022-01-25T08:52:01Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/33229",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20combinatorial%20designs",
    "label_color": "0000ff",
    "label_name": "c: combinatorial designs",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33229#event-454930"
}
```



---

archive/issue_events_454931.json:
```json
{
    "actor": "https://github.com/MathieuDutSik",
    "created_at": "2022-01-25T08:52:01Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/33229",
    "label": "https://github.com/sagemath/sage/labels/p%3A%20major%20/%203",
    "label_color": "ffbb00",
    "label_name": "p: major / 3",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33229#event-454931"
}
```



---

archive/issue_events_454932.json:
```json
{
    "actor": "https://github.com/MathieuDutSik",
    "created_at": "2022-01-25T08:52:01Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/33229",
    "label": "https://github.com/sagemath/sage/labels/bug",
    "label_color": "d73a4a",
    "label_name": "bug",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33229#event-454932"
}
```



---

archive/issue_comments_537228.json:
```json
{
    "body": "Description changed:\n``````diff\n--- \n+++ \n@@ -1,6 +1,18 @@\n-The command that crash is just\n+In Sage 9.5.rc1, the following command causes a crash:\n \n-C = codes.BinaryReedMullerCode(16, 32)\n+```\n+sage: C = codes.BinaryReedMullerCode(16, 32)\n+------------------------------------------------------------------------\n+(no backtrace available)\n+------------------------------------------------------------------------\n+Unhandled SIGSEGV: A segmentation fault occurred.\n+This probably occurred because a *compiled* module has a bug\n+in it and is not properly wrapped with sig_on(), sig_off().\n+Python will now terminate.\n+------------------------------------------------------------------------\n+.../src/bin/sage-python: line 2: 60716 Segmentation fault: 11  sage -python \"$@\"\n+```\n \n-I am not sure if the input is valid. But if to, we should not get a crash I believe, but an error.\n+In case the input is invalid, an error\n+would be preferable to a crash.\n \n``````\n",
    "created_at": "2022-01-25T10:25:38Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33229",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33229#issuecomment-537228",
    "user": "https://github.com/slel"
}
```

Description changed:
``````diff
--- 
+++ 
@@ -1,6 +1,18 @@
-The command that crash is just
+In Sage 9.5.rc1, the following command causes a crash:
 
-C = codes.BinaryReedMullerCode(16, 32)
+```
+sage: C = codes.BinaryReedMullerCode(16, 32)
+------------------------------------------------------------------------
+(no backtrace available)
+------------------------------------------------------------------------
+Unhandled SIGSEGV: A segmentation fault occurred.
+This probably occurred because a *compiled* module has a bug
+in it and is not properly wrapped with sig_on(), sig_off().
+Python will now terminate.
+------------------------------------------------------------------------
+.../src/bin/sage-python: line 2: 60716 Segmentation fault: 11  sage -python "$@"
+```
 
-I am not sure if the input is valid. But if to, we should not get a crash I believe, but an error.
+In case the input is invalid, an error
+would be preferable to a crash.
 
``````




---

archive/issue_comments_537229.json:
```json
{
    "body": "Changed keywords from none to **segfault**",
    "created_at": "2022-01-25T10:26:03Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/33229",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/33229#issuecomment-537229",
    "user": "https://github.com/slel"
}
```

Changed keywords from none to **segfault**



---

archive/issue_events_454933.json:
```json
{
    "actor": "https://github.com/slel",
    "created_at": "2022-01-25T10:26:21Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/33229",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20combinatorial%20designs",
    "label_color": "0000ff",
    "label_name": "c: combinatorial designs",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33229#event-454933"
}
```



---

archive/issue_events_454934.json:
```json
{
    "actor": "https://github.com/slel",
    "created_at": "2022-01-25T10:26:21Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/33229",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20coding%20theory",
    "label_color": "0000ff",
    "label_name": "c: coding theory",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33229#event-454934"
}
```



---

archive/issue_events_454935.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-05-03T15:17:06Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/33229",
    "milestone_number": null,
    "milestone_title": "sage-9.6",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33229#event-454935"
}
```



---

archive/issue_events_454936.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-05-03T15:17:06Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/33229",
    "milestone_number": null,
    "milestone_title": "sage-9.7",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33229#event-454936"
}
```



---

archive/issue_events_454937.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-09-19T18:58:47Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/33229",
    "milestone_number": null,
    "milestone_title": "sage-9.7",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33229#event-454937"
}
```



---

archive/issue_events_454938.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-09-19T18:58:47Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/33229",
    "milestone_number": null,
    "milestone_title": "sage-9.8",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33229#event-454938"
}
```



---

archive/issue_events_454939.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2023-01-29T23:06:23Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/33229",
    "milestone_number": null,
    "milestone_title": "sage-9.8",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/33229#event-454939"
}
```
