# Issue 24221: py3: ZZ for large int

archive/issues_023984.json:
```json
{
    "body": "in a python3-build-sage:\n\n```\nsage: ZZ(int(2**62))\n4611686018427387904\nsage: ZZ(int(2**63))\n---------------------------------------------------------------------------\nOverflowError                             Traceback (most recent call last)\nOverflowError: Python int too large to convert to C long\n\nThe above exception was the direct cause of the following exception:\n\nSystemError                               Traceback (most recent call last)\n<ipython-input-41-47ff15a43d5f> in <module>()\n----> 1 ZZ(int(Integer(2)**Integer(64)))\n\nSystemError: Integer Ring returned a result with an error set\nsage: int(2**63)\n18446744073709551616\n```\nrelated to #16072\n\n**CC:**  @jdemeyer @embray\n\n**Branch/Commit:** [190a90c048520bb954d1a41757f646f9c3ec8b30](https://github.com/sagemath/sagetrac-mirror/commit/190a90c048520bb954d1a41757f646f9c3ec8b30)\n\n**Reviewer:** Fr\u00e9d\u00e9ric Chapoton\n\n**Author:** Jeroen Demeyer\n\nIssue created by migration from https://trac.sagemath.org/ticket/24221\n\n",
    "closed_at": "2017-12-11T01:02:19Z",
    "created_at": "2017-11-16T10:44:05Z",
    "labels": [
        "component: python3",
        "enhancement"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-8.1",
    "title": "py3: ZZ for large int",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/24221",
    "user": "https://github.com/fchapoton"
}
```
in a python3-build-sage:

```
sage: ZZ(int(2**62))
4611686018427387904
sage: ZZ(int(2**63))
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
OverflowError: Python int too large to convert to C long

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-41-47ff15a43d5f> in <module>()
----> 1 ZZ(int(Integer(2)**Integer(64)))

SystemError: Integer Ring returned a result with an error set
sage: int(2**63)
18446744073709551616
```
related to #16072

**CC:**  @jdemeyer @embray

**Branch/Commit:** [190a90c048520bb954d1a41757f646f9c3ec8b30](https://github.com/sagemath/sagetrac-mirror/commit/190a90c048520bb954d1a41757f646f9c3ec8b30)

**Reviewer:** Frédéric Chapoton

**Author:** Jeroen Demeyer

Issue created by migration from https://trac.sagemath.org/ticket/24221





---

archive/issue_comments_369005.json:
```json
{
    "body": "**Description changed:**\n``````diff\n--- \n+++ \n@@ -18,3 +18,4 @@\n sage: int(2**63)\n 18446744073709551616\n ```\n+related to #16072\n``````\n",
    "created_at": "2017-11-16T10:44:51Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369005",
    "user": "https://github.com/fchapoton"
}
```

**Description changed:**
``````diff
--- 
+++ 
@@ -18,3 +18,4 @@
 sage: int(2**63)
 18446744073709551616
 ```
+related to #16072
``````




---

archive/issue_comments_369006.json:
```json
{
    "body": "<a id='comment:2'></a>\nIs the text that you quoted above the **literal** text that you see on your screen? Just wondering why there is no traceback shown...",
    "created_at": "2017-11-16T10:50:39Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369006",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:2'></a>
Is the text that you quoted above the **literal** text that you see on your screen? Just wondering why there is no traceback shown...



---

archive/issue_comments_369007.json:
```json
{
    "body": "<a id='comment:3'></a>\nyes, this the **literal** text that I see in my terminal. No better traceback.\n\nBy the way, maybe you should try by yourself to use the branch public/python3-experiment-8.1.rc1 ?",
    "created_at": "2017-11-16T10:53:44Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369007",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:3'></a>
yes, this the **literal** text that I see in my terminal. No better traceback.

By the way, maybe you should try by yourself to use the branch public/python3-experiment-8.1.rc1 ?



---

archive/issue_comments_369008.json:
```json
{
    "body": "**Branch:** [u/jdemeyer/py3__zz_for_large_int](https://github.com/sagemath/sagetrac-mirror/tree/u/jdemeyer/py3__zz_for_large_int)",
    "created_at": "2017-11-16T10:54:45Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369008",
    "user": "https://github.com/jdemeyer"
}
```

**Branch:** [u/jdemeyer/py3__zz_for_large_int](https://github.com/sagemath/sagetrac-mirror/tree/u/jdemeyer/py3__zz_for_large_int)



---

archive/issue_comments_369009.json:
```json
{
    "body": "**Commit:** [f27e59b360c8a73d23cb4e108922197afbaa00ac](https://github.com/sagemath/sagetrac-mirror/commit/f27e59b360c8a73d23cb4e108922197afbaa00ac)",
    "created_at": "2017-11-16T11:03:16Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369009",
    "user": "https://github.com/jdemeyer"
}
```

**Commit:** [f27e59b360c8a73d23cb4e108922197afbaa00ac](https://github.com/sagemath/sagetrac-mirror/commit/f27e59b360c8a73d23cb4e108922197afbaa00ac)



---

archive/issue_comments_369010.json:
```json
{
    "body": "<a id='comment:5'></a>\nThere is a general pattern here:\n\nIn Cython code in Sage, when checking for an `int`-like object, this is often done like\n\n```\nif isinstance(x, int):\n    # Handle int\nelif isinstance(x, long):\n    # Handle long\n```\n\nThis works fine in Python 2 because `int` and `long` are distinct types. In Python 3, there is only one type, which is the `long` type from Python 2 but which is called `int` in Python 3 (similar to how the `unicode` type from Python 2 is called `str` in Python 3).\n\nNow Cython understands the name `long` to refer to the type which is called `long` in Python 2 and `int` in Python 3. It also understands `int` to refer to the type which is called `int` in Python 2 and the *different* type which is called `int` in Python 3.\n\nSo, in Cython code for Python 3, the checks `isinstance(x, int)` and `isinstance(x, long)` are equivalent. However, the code which needs to be executed is the code for the `long` type, so we should do that check first.\n\n---\n**New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/f27e59b360c8a73d23cb4e108922197afbaa00ac\">f27e59b</a></td><td><code>Check \"long\" before \"int\"</code></td></tr></table>\n",
    "created_at": "2017-11-16T11:03:16Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369010",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:5'></a>
There is a general pattern here:

In Cython code in Sage, when checking for an `int`-like object, this is often done like

```
if isinstance(x, int):
    # Handle int
elif isinstance(x, long):
    # Handle long
```

This works fine in Python 2 because `int` and `long` are distinct types. In Python 3, there is only one type, which is the `long` type from Python 2 but which is called `int` in Python 3 (similar to how the `unicode` type from Python 2 is called `str` in Python 3).

Now Cython understands the name `long` to refer to the type which is called `long` in Python 2 and `int` in Python 3. It also understands `int` to refer to the type which is called `int` in Python 2 and the *different* type which is called `int` in Python 3.

So, in Cython code for Python 3, the checks `isinstance(x, int)` and `isinstance(x, long)` are equivalent. However, the code which needs to be executed is the code for the `long` type, so we should do that check first.

---
**New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f27e59b360c8a73d23cb4e108922197afbaa00ac">f27e59b</a></td><td><code>Check "long" before "int"</code></td></tr></table>




---

archive/issue_comments_369011.json:
```json
{
    "body": "**Author:** Jeroen Demeyer",
    "created_at": "2017-11-16T11:03:16Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369011",
    "user": "https://github.com/jdemeyer"
}
```

**Author:** Jeroen Demeyer



---

archive/issue_events_217075.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2017-11-16T11:03:16Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24221#event-217075"
}
```



---

archive/issue_comments_369012.json:
```json
{
    "body": "<a id='comment:6'></a>\nThis does not fix the issue:\n\n```\nsage: ZZ(int(2**63))\n---------------------------------------------------------------------------\nOverflowError                             Traceback (most recent call last)\nOverflowError: Python int too large to convert to C long\n\nThe above exception was the direct cause of the following exception:\n\nSystemError                               Traceback (most recent call last)\n<ipython-input-3-9949e9fafd8e> in <module>()\n----> 1 ZZ(int(Integer(2)**Integer(63)))\n\nSystemError: Integer Ring returned a result with an error set\n```",
    "created_at": "2017-11-16T12:23:48Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369012",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:6'></a>
This does not fix the issue:

```
sage: ZZ(int(2**63))
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
OverflowError: Python int too large to convert to C long

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-3-9949e9fafd8e> in <module>()
----> 1 ZZ(int(Integer(2)**Integer(63)))

SystemError: Integer Ring returned a result with an error set
```



---

archive/issue_comments_369013.json:
```json
{
    "body": "<a id='comment:7'></a>\nSorry, I can't help further without a traceback.",
    "created_at": "2017-11-16T12:32:12Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369013",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:7'></a>
Sorry, I can't help further without a traceback.



---

archive/issue_comments_369014.json:
```json
{
    "body": "**Changing commit** from \"[f27e59b360c8a73d23cb4e108922197afbaa00ac](https://github.com/sagemath/sagetrac-mirror/commit/f27e59b360c8a73d23cb4e108922197afbaa00ac)\" to \"[190a90c048520bb954d1a41757f646f9c3ec8b30](https://github.com/sagemath/sagetrac-mirror/commit/190a90c048520bb954d1a41757f646f9c3ec8b30)\".",
    "created_at": "2017-11-16T12:36:05Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369014",
    "user": "https://trac.sagemath.org/admin/accounts/users/git"
}
```

**Changing commit** from "[f27e59b360c8a73d23cb4e108922197afbaa00ac](https://github.com/sagemath/sagetrac-mirror/commit/f27e59b360c8a73d23cb4e108922197afbaa00ac)" to "[190a90c048520bb954d1a41757f646f9c3ec8b30](https://github.com/sagemath/sagetrac-mirror/commit/190a90c048520bb954d1a41757f646f9c3ec8b30)".



---

archive/issue_comments_369015.json:
```json
{
    "body": "<a id='comment:8'></a>\n**Branch pushed to git repo; I updated commit sha1. This was a forced push.** **New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/190a90c048520bb954d1a41757f646f9c3ec8b30\">190a90c</a></td><td><code>Check \"long\" before \"int\"</code></td></tr></table>\n",
    "created_at": "2017-11-16T12:36:05Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369015",
    "user": "https://trac.sagemath.org/admin/accounts/users/git"
}
```

<a id='comment:8'></a>
**Branch pushed to git repo; I updated commit sha1. This was a forced push.** **New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/190a90c048520bb954d1a41757f646f9c3ec8b30">190a90c</a></td><td><code>Check "long" before "int"</code></td></tr></table>




---

archive/issue_comments_369016.json:
```json
{
    "body": "<a id='comment:9'></a>\nNever mind, I just realized that the example uses coercion, not direct initialization of an `Integer`.",
    "created_at": "2017-11-16T12:36:42Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369016",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:9'></a>
Never mind, I just realized that the example uses coercion, not direct initialization of an `Integer`.



---

archive/issue_comments_369017.json:
```json
{
    "body": "<a id='comment:10'></a>\nIndeed\n\n```\nsage: ZZ(2**63)\n9223372036854775808\n```\ndoes work (at least with you change)",
    "created_at": "2017-11-16T12:38:23Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369017",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:10'></a>
Indeed

```
sage: ZZ(2**63)
9223372036854775808
```
does work (at least with you change)



---

archive/issue_comments_369018.json:
```json
{
    "body": "<a id='comment:11'></a>\nThat fixes the issue ! Thanks !",
    "created_at": "2017-11-16T12:40:58Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369018",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:11'></a>
That fixes the issue ! Thanks !



---

archive/issue_events_217076.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2017-11-16T13:03:00Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24221#event-217076"
}
```



---

archive/issue_events_217077.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2017-11-16T13:03:00Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24221#event-217077"
}
```



---

archive/issue_comments_369019.json:
```json
{
    "body": "**Reviewer:** Fr\u00e9d\u00e9ric Chapoton",
    "created_at": "2017-11-16T13:03:00Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369019",
    "user": "https://github.com/fchapoton"
}
```

**Reviewer:** Frédéric Chapoton



---

archive/issue_comments_369020.json:
```json
{
    "body": "<a id='comment:13'></a>\nThere will certainly be more places in Sage with the same bug. But the solution should be the same: whenever you want to check `int` and `long`, check `long` first.",
    "created_at": "2017-11-16T13:05:39Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369020",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:13'></a>
There will certainly be more places in Sage with the same bug. But the solution should be the same: whenever you want to check `int` and `long`, check `long` first.



---

archive/issue_comments_369021.json:
```json
{
    "body": "<a id='comment:14'></a>\nSee also #23792",
    "created_at": "2017-11-16T13:10:07Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369021",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:14'></a>
See also #23792



---

archive/issue_comments_369022.json:
```json
{
    "body": "<a id='comment:15'></a>\nfollow up in #24225",
    "created_at": "2017-11-16T13:18:50Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369022",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:15'></a>
follow up in #24225



---

archive/issue_events_217078.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2017-11-16T16:07:34Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24221#event-217078"
}
```



---

archive/issue_events_217079.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2017-11-16T16:07:34Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "label": "needs work",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24221#event-217079"
}
```



---

archive/issue_comments_369023.json:
```json
{
    "body": "<a id='comment:16'></a>\nok, let us use the opportuniy here to make some similar changes in the same file",
    "created_at": "2017-11-16T16:07:34Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369023",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:16'></a>
ok, let us use the opportuniy here to make some similar changes in the same file



---

archive/issue_comments_369024.json:
```json
{
    "body": "<a id='comment:17'></a>\n**New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/0fb286dda3a0f88c3336153f7996cba676046bc5\">0fb286d</a></td><td><code>trac 24221 Eric's suggestions of additional changes</code></td></tr></table>\n",
    "created_at": "2017-11-16T16:11:32Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369024",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:17'></a>
**New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0fb286dda3a0f88c3336153f7996cba676046bc5">0fb286d</a></td><td><code>trac 24221 Eric's suggestions of additional changes</code></td></tr></table>




---

archive/issue_events_217080.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2017-11-16T16:11:32Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "label": "needs work",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24221#event-217080"
}
```



---

archive/issue_events_217081.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2017-11-16T16:11:32Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24221#event-217081"
}
```



---

archive/issue_comments_369025.json:
```json
{
    "body": "**Changing branch** from \"[u/jdemeyer/py3__zz_for_large_int](https://github.com/sagemath/sagetrac-mirror/tree/u/jdemeyer/py3__zz_for_large_int)\" to \"[public/longint24221](https://github.com/sagemath/sagetrac-mirror/tree/public/longint24221)\".",
    "created_at": "2017-11-16T16:11:32Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369025",
    "user": "https://github.com/fchapoton"
}
```

**Changing branch** from "[u/jdemeyer/py3__zz_for_large_int](https://github.com/sagemath/sagetrac-mirror/tree/u/jdemeyer/py3__zz_for_large_int)" to "[public/longint24221](https://github.com/sagemath/sagetrac-mirror/tree/public/longint24221)".



---

archive/issue_comments_369026.json:
```json
{
    "body": "**Changing commit** from \"[190a90c048520bb954d1a41757f646f9c3ec8b30](https://github.com/sagemath/sagetrac-mirror/commit/190a90c048520bb954d1a41757f646f9c3ec8b30)\" to \"[0fb286dda3a0f88c3336153f7996cba676046bc5](https://github.com/sagemath/sagetrac-mirror/commit/0fb286dda3a0f88c3336153f7996cba676046bc5)\".",
    "created_at": "2017-11-16T16:11:32Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369026",
    "user": "https://github.com/fchapoton"
}
```

**Changing commit** from "[190a90c048520bb954d1a41757f646f9c3ec8b30](https://github.com/sagemath/sagetrac-mirror/commit/190a90c048520bb954d1a41757f646f9c3ec8b30)" to "[0fb286dda3a0f88c3336153f7996cba676046bc5](https://github.com/sagemath/sagetrac-mirror/commit/0fb286dda3a0f88c3336153f7996cba676046bc5)".



---

archive/issue_comments_369027.json:
```json
{
    "body": "**Changing commit** from \"[0fb286dda3a0f88c3336153f7996cba676046bc5](https://github.com/sagemath/sagetrac-mirror/commit/0fb286dda3a0f88c3336153f7996cba676046bc5)\" to \"[190a90c048520bb954d1a41757f646f9c3ec8b30](https://github.com/sagemath/sagetrac-mirror/commit/190a90c048520bb954d1a41757f646f9c3ec8b30)\".",
    "created_at": "2017-11-16T16:39:26Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369027",
    "user": "https://github.com/jdemeyer"
}
```

**Changing commit** from "[0fb286dda3a0f88c3336153f7996cba676046bc5](https://github.com/sagemath/sagetrac-mirror/commit/0fb286dda3a0f88c3336153f7996cba676046bc5)" to "[190a90c048520bb954d1a41757f646f9c3ec8b30](https://github.com/sagemath/sagetrac-mirror/commit/190a90c048520bb954d1a41757f646f9c3ec8b30)".



---

archive/issue_events_217082.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2017-11-16T16:39:26Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24221#event-217082"
}
```



---

archive/issue_events_217083.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2017-11-16T16:39:26Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24221#event-217083"
}
```



---

archive/issue_comments_369028.json:
```json
{
    "body": "<a id='comment:18'></a>\nMoving the follow-up changes to #24227.",
    "created_at": "2017-11-16T16:39:26Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369028",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:18'></a>
Moving the follow-up changes to #24227.



---

archive/issue_comments_369029.json:
```json
{
    "body": "**Changing branch** from \"[public/longint24221](https://github.com/sagemath/sagetrac-mirror/tree/public/longint24221)\" to \"[u/jdemeyer/py3__zz_for_large_int](https://github.com/sagemath/sagetrac-mirror/tree/u/jdemeyer/py3__zz_for_large_int)\".",
    "created_at": "2017-11-16T16:39:26Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369029",
    "user": "https://github.com/jdemeyer"
}
```

**Changing branch** from "[public/longint24221](https://github.com/sagemath/sagetrac-mirror/tree/public/longint24221)" to "[u/jdemeyer/py3__zz_for_large_int](https://github.com/sagemath/sagetrac-mirror/tree/u/jdemeyer/py3__zz_for_large_int)".



---

archive/issue_comments_369030.json:
```json
{
    "body": "**Changing branch** from \"[u/jdemeyer/py3__zz_for_large_int](https://github.com/sagemath/sagetrac-mirror/tree/u/jdemeyer/py3__zz_for_large_int)\" to \"[190a90c048520bb954d1a41757f646f9c3ec8b30](https://github.com/sagemath/sagetrac-mirror/commit/190a90c048520bb954d1a41757f646f9c3ec8b30)\".",
    "created_at": "2017-12-11T01:02:19Z",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24221#issuecomment-369030",
    "user": "https://github.com/vbraun"
}
```

**Changing branch** from "[u/jdemeyer/py3__zz_for_large_int](https://github.com/sagemath/sagetrac-mirror/tree/u/jdemeyer/py3__zz_for_large_int)" to "[190a90c048520bb954d1a41757f646f9c3ec8b30](https://github.com/sagemath/sagetrac-mirror/commit/190a90c048520bb954d1a41757f646f9c3ec8b30)".



---

archive/issue_events_217084.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2017-12-11T01:02:19Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24221#event-217084"
}
```



---

archive/issue_events_217085.json:
```json
{
    "actor": "https://github.com/vbraun",
    "commit_id": "eac1112a10ec21cd73aa6ca0ab158cb0a14b4c59",
    "created_at": "2017-12-11T01:02:19Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/24221",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24221#event-217085"
}
```
